name: Auto merger

on:
  issue_comment:
    types: [edited]

jobs:
  auto-merge-pr:
    name: Auto Merge PR
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, 'review-fixed')
    
    permissions:
      contents: write
      pull-requests: write
      issues: write
      actions: read
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 1

      - name: Approve PR
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          echo "Approving PR #${{ github.event.issue.number }}"
          gh pr review ${{ github.event.issue.number }} --approve

      - name: Merge PR
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          echo "Merging PR #${{ github.event.issue.number }}"
          gh pr merge ${{ github.event.issue.number }} --merge --auto