name: Claude Auto Review

on:
  pull_request:
    types: [synchronize, labeled]

jobs:
  auto-review:
    runs-on: ubuntu-latest

    if: |
      (
        github.event.action == 'synchronize' &&
        contains(github.event.pull_request.labels.*.name, 'ci-passed') &&
        !contains(github.event.pull_request.labels.*.name, 'review-fixed') &&
        !contains(github.event.pull_request.labels.*.name, 'reviewed')
      )
      ||
      (
        github.event.action == 'labeled' &&
        contains(github.event.pull_request.labels.*.name, 'ci-passed') &&
        !contains(github.event.pull_request.labels.*.name, 'review-fixed') &&
        !contains(github.event.pull_request.labels.*.name, 'reviewed')
      )

    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Automatic PR Review
        
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          timeout_minutes: "60"
          direct_prompt: |
            Please review this pull request and provide comprehensive feedback.

            Focus on:
            - Code quality and best practices
            - Potential bugs or issues
            - Performance considerations
            - Security implications
            - Test coverage
            - Documentation updates if needed
            - YAGNI（You Aren't Gonna Need It）：今必要じゃない機能は作らない
            - DRY（Don't Repeat Yourself）：同じコードを繰り返さない
            - KISS（Keep It Simple Stupid）：シンプルに保つ
            - t-wada TDD: テスト駆動開発

            Provide constructive feedback with specific suggestions for improvement.
            Use inline comments to highlight specific areas of concern.
          # allowed_tools: "mcp__github__create_pending_pull_request_review,mcp__github__add_pull_request_review_comment_to_pending_review,mcp__github__submit_pending_pull_request_review,mcp__github__get_pull_request_diff"

      - name: Add reviewed Label
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            // pull_requestイベントから直接PR番号を取得
            const prNumber = context.payload.pull_request.number;
            console.log(`Adding reviewed label to PR #${prNumber}`);
            
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              labels: ['reviewed']
            });
            
            console.log(`Added reviewed label to PR #${prNumber}`);


            