name: Claude Review Fix

on:
  pull_request:
    types: [synchronize, labeled]

jobs:
  claude-Review-fix:
    name: Claude Review Fix
    runs-on: ubuntu-latest
    
    if: |
      (github.event.action == 'labeled' && github.event.label.name == 'reviewed') ||
      (github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'reviewed'))
    
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 1

      - name: Remove Review and CI-Passed Labels
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            
            // reviewed ラベルを削除
            try {
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                name: 'reviewed'
              });
              console.log('Removed reviewed label');
            } catch (error) {
              console.log('reviewed label not found or already removed');
            }
            
            // ci-passed ラベルを削除
            try {
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                name: 'ci-passed'
              });
              console.log('Removed ci-passed label');
            } catch (error) {
              console.log('ci-passed label not found or already removed');
            }

      - name: Run Claude Code for Review Fix
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          
          additional_permissions: |
            actions: read
          
          direct_prompt: |
            PRのレビューが完了しています。以下の点を確認してください：
            - レビュー結果を確認し、必要な修正を行ってコミットしてください
            - 修正が完了したら、PRを更新してください
            - 今後の課題がある場合は、issueを作成してください
            - ドキュメント推奨事項を確認し、必要に応じて更新してください
            - これ以上修正が必要ない場合は、 review-fixed とコメントを追加してください

      